// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rabbit-test-worker.proto

/*
Package rabbittest is a generated protocol buffer package.

It is generated from these files:
	rabbit-test-worker.proto
	rabbit-test.proto

It has these top-level messages:
	NodeStatus
	Empty
	RegisterNodeRequest
	RegisterNodeReply
*/
package rabbittest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeStatus_Status int32

const (
	NodeStatus_READY   NodeStatus_Status = 0
	NodeStatus_SLEEP   NodeStatus_Status = 1
	NodeStatus_WORKING NodeStatus_Status = 2
)

var NodeStatus_Status_name = map[int32]string{
	0: "READY",
	1: "SLEEP",
	2: "WORKING",
}
var NodeStatus_Status_value = map[string]int32{
	"READY":   0,
	"SLEEP":   1,
	"WORKING": 2,
}

func (x NodeStatus_Status) String() string {
	return proto.EnumName(NodeStatus_Status_name, int32(x))
}
func (NodeStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type NodeStatus struct {
	Status NodeStatus_Status `protobuf:"varint,1,opt,name=status,enum=rabbittest.NodeStatus_Status" json:"status,omitempty"`
}

func (m *NodeStatus) Reset()                    { *m = NodeStatus{} }
func (m *NodeStatus) String() string            { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()               {}
func (*NodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeStatus) GetStatus() NodeStatus_Status {
	if m != nil {
		return m.Status
	}
	return NodeStatus_READY
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*NodeStatus)(nil), "rabbittest.NodeStatus")
	proto.RegisterType((*Empty)(nil), "rabbittest.Empty")
	proto.RegisterEnum("rabbittest.NodeStatus_Status", NodeStatus_Status_name, NodeStatus_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Worker service

type WorkerClient interface {
	CheckStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) CheckStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := grpc.Invoke(ctx, "/rabbittest.Worker/CheckStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Worker service

type WorkerServer interface {
	CheckStatus(context.Context, *Empty) (*NodeStatus, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rabbittest.Worker/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).CheckStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rabbittest.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStatus",
			Handler:    _Worker_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rabbit-test-worker.proto",
}

func init() { proto.RegisterFile("rabbit-test-worker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4a, 0x4c, 0x4a,
	0xca, 0x2c, 0xd1, 0x2d, 0x49, 0x2d, 0x2e, 0xd1, 0x2d, 0xcf, 0x2f, 0xca, 0x4e, 0x2d, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x82, 0xc8, 0x80, 0x24, 0x94, 0x0a, 0xb8, 0xb8, 0xfc, 0xf2,
	0x53, 0x52, 0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0x4c, 0xb9, 0xd8, 0x8a, 0xc1, 0x2c, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x59, 0x3d, 0x84, 0x52, 0x3d, 0x84, 0x3a, 0x3d, 0x08, 0x15,
	0x04, 0x55, 0xac, 0xa4, 0xcd, 0xc5, 0x06, 0x35, 0x80, 0x93, 0x8b, 0x35, 0xc8, 0xd5, 0xd1, 0x25,
	0x52, 0x80, 0x01, 0xc4, 0x0c, 0xf6, 0x71, 0x75, 0x0d, 0x10, 0x60, 0x14, 0xe2, 0xe6, 0x62, 0x0f,
	0xf7, 0x0f, 0xf2, 0xf6, 0xf4, 0x73, 0x17, 0x60, 0x52, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28,
	0xa9, 0x34, 0x72, 0xe1, 0x62, 0x0b, 0x07, 0x3b, 0x4b, 0xc8, 0x8a, 0x8b, 0xdb, 0x39, 0x23, 0x35,
	0x39, 0x1b, 0x6a, 0x88, 0x20, 0xb2, 0xad, 0x60, 0xb5, 0x52, 0x62, 0xd8, 0x1d, 0xa2, 0xc4, 0x90,
	0xc4, 0x06, 0xf6, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x87, 0x8b, 0xb0, 0x63, 0xef, 0x00,
	0x00, 0x00,
}
